# Site Configuration File
#
# Site settings
locale: "en-US"
title: Laptop Chemistry
site_theme: default
name: &name Brad Dallin
email: &email bradley.dallin.phd@gmail.com
description: >-
  My digital workspace for computational chemistry research,
  cheminformatics tools, and scientific computing projects.
  Sharing thoughts on methods, discoveries, and open source
  contributions that catch my attention in the world of scientific
  computing.
url: https://brad-dallin.github.io
baseurl: ""
repository: brad-dallin/brad-dallin.github.io


# Author settings
author: 
  name: *name
  email: *email
  contact:
    - title: Mail
      icon: fa-solid fa-envelope
      url: mailto:*email
    - title: GitHub
      icon: fa-brands fa-github
      url: https://github.com/brad-dallin
    - title: LinkedIn
      icon: fa-brands fa-linkedin
      url: https://www.linkedin.com/in/bradley-dallin/


# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag


# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :


# Analytics
analytics:
  provider               :  "false" # false (default), "google", "google-universal", "google-analytics-4", "custom"
  google:
    tracking_id          :

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/


## Github pages fixed on deployment
# lsi: false
# safe: true
# source:
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge