# Jekyll Configuration

# Site settings
title: Laptop Drug Hunting
description: >-
  This is a blog exploring topics I find interesting in drug hunting
  requiring no more compute power than a semi-reliable laptop.

# Author
author:
  name: Bradley Dallin, PhD
  email: bradley.dallin.phd@gmail.com

social_links:
  - title: GitHub
    icon: github
    url: https://github.com/brad-dallin
  - title: LinkedIn
    icon: linkedin
    url: https://www.linkedin.com/in/brad-dallin

# Hide email
hide_site_email_link: true

# Hide RSS feed
hide_site_feed_link: false

# Build settings
plugins:
 - jekyll-feed
 - jekyll-seo-tag

# Google analytics
google_analytics: G-V4CYE1QFLX

# Skin selection. Available skins are:
#   * auto               Adaptive skin based on the classic and dark skins.
#   * light              Default, light color scheme.
#   * dark               Dark variant of the classic skin.
#   * solarized-light    Light variant of solarized color scheme.
#   * solarized-dark     Dark variant of solarized color scheme.
#   * solarized          Adaptive skin for solarized color scheme skins.
skin: auto

# Specific site navigation
nav_pages:
  - blog.md
  - about.md

# Set to `true` to show excerpts on the homepage.
show_excerpts: false

# Date format
date_format: "%b %d, %Y"

# Include
# include:
#   - /assets/favicon/favicon.ico
